# Generated by Django 4.2.6 on 2023-10-11 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_auto_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Jeep', 'Jeep')], default='Jeep', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,20}$', 'First letter uppercase min 2 max 20 ch')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
