# Generated by Django 4.2.6 on 2024-01-25 12:08

import core.services.s3_service

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_carmodel_photo_alter_carmodel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimagesmodel',
            name='photo',
        ),
        migrations.AddField(
            model_name='carimagesmodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, storage=core.services.s3_service.CarStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
