# Generated by Django 4.2.6 on 2024-01-31 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_carimagesmodel_photo_carimagesmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Eur'), ('UAH', 'Uah'), ('USD', 'Usd')], default='USD', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CarCurrencyPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('EUR', 'Eur'), ('UAH', 'Uah'), ('USD', 'Usd')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_currency_prices', to='cars.carmodel')),
            ],
            options={
                'db_table': 'car_currency_price',
            },
        ),
    ]
