# Generated by Django 4.2.6 on 2024-06-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_carmodel_price_convertor_carmodel_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='region',
            field=models.CharField(choices=[('Volyn', 'Volyn'), ('Lviv', 'Lviv'), ('Rivne', 'Rivne'), ('Kyiv', 'Kyiv')],
                                   default='Volyn', max_length=20),
            preserve_default=False,
        ),
    ]
