# Generated by Django 4.2.6 on 2024-06-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_carmodel_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
