# Generated by Django 4.2.6 on 2024-06-05 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0011_carmodel_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='views',
        ),
        migrations.CreateModel(
            name='CarDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_details', to='cars.carmodel')),
                ('user_viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_details',
            },
        ),
    ]
