# Generated by Django 4.2.6 on 2024-01-09 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usermodel_is_active_alter_usermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{1,49}$', ['First letter uppercase', 'min 2 max 50 characters'])]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{1,49}$', ['First letter uppercase', 'min 2 max 50 characters'])]),
        ),
    ]
