# Generated by Django 4.2.6 on 2024-11-26 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_usermodel_first_name_usermodel_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
    ]
