# Generated by Django 4.2.6 on 2023-10-18 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_usermodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[А-ЯЁІЇЄҐ][а-яіїєґё]{1,49}$', ['Only cyrillic', 'First letter uppercase', 'min 2 max 50 characters'])]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[А-ЯЁІЇЄҐ][а-яіїєґё]{1,49}$', ['Only cyrillic', 'First letter uppercase', 'min 2 max 50 characters'])]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*\\d)(?=.*[`~!@#$%^&*()_\\-+=\\\\|\\[\\]{};:\\\'"\\/\\?\\.>,<])[a-zA-Z\\d`~!@#$%^&*()_\\-+=\\\\|\\[\\]{};:\\\'"\\/\\?\\.>,<]{8,30}$', ['min 1 lowercase', 'min 1 uppercase', 'min 1 digit', 'min 1 special character', 'length 8-30 ch'])]),
        ),
    ]
