# Generated by Django 4.2.6 on 2024-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangePriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usd_exchange_buy', models.FloatField()),
                ('usd_exchange_sale', models.FloatField()),
                ('eur_exchange_buy', models.FloatField()),
                ('eur_exchange_sale', models.FloatField()),
                ('usd_eur_exchange_buy', models.FloatField()),
                ('usd_eur_exchange_sale', models.FloatField()),
            ],
            options={
                'db_table': 'price_convertor',
                'ordering': ['id'],
            },
        ),
    ]
