# Generated by Django 4.2.6 on 2024-01-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_convertor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ccy', models.CharField(choices=[('EUR', 'Eur'), ('UAH', 'Uah'), ('USD', 'Usd')], max_length=3)),
                ('base_ccy', models.CharField(choices=[('EUR', 'Eur'), ('UAH', 'Uah'), ('USD', 'Usd')], max_length=3)),
                ('buy', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sale', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'exchange_rate',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='ExchangePriceModel',
        ),
    ]
