# Generated by Django 4.2.6 on 2024-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_convertor', '0002_exchangeratemodel_delete_exchangepricemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateISOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currencyCodeA', models.CharField(choices=[('978', 'Eur'), ('980', 'Uah'), ('840', 'Usd')], max_length=3)),
                ('currencyCodeB', models.CharField(choices=[('978', 'Eur'), ('980', 'Uah'), ('840', 'Usd')], max_length=3)),
                ('rateBuy', models.DecimalField(decimal_places=5, max_digits=15)),
                ('rateSell', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
            options={
                'db_table': 'exchange_rate_iso',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='exchangeratemodel',
            name='buy',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='exchangeratemodel',
            name='sale',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
